###############################################################################
#        _       _             _   _            _____  _
#       | |     | |           | | | |          |  __ \(_)
#       | | ___ | |__  _ __   | |_| |__   ___  | |__) |_ _ __  _ __   ___ _ __
#   _   | |/ _ \| '_ \| '_ \  | __| '_ \ / _ \ |  _  /| | '_ \| '_ \ / _ \ '__|
#  | |__| | (_) | | | | | | | | |_| | | |  __/ | | \ \| | |_) | |_) |  __/ |
#   \____/ \___/|_| |_|_| |_|  \__|_| |_|\___| |_|  \_\_| .__/| .__/ \___|_|
#                                                       | |   | |
#                                                       |_|   |_|
#
# Copyright (c) 2023 Claudio Andr√© <claudioandre.br at gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
###############################################################################
# Bitrise CI configuration
# More info at https://github.com/openwall/john-packages
# Bitrise validation conflicts with our linters, but the difference is basically spaces

---
format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
app:
  envs:
    - default_apk_name: john-app.apk
    - TARGET_ARCH: NIX
    - EXTRA: full;extra
    # BUILD_OPTS: --disable-native-tests --build=arm-linux-gnueabi
    #   => FAILS: --build=aarch64-linux-gnueabi
    #               (pseudo_intrinsics.h:48:22: fatal error: arm_neon.h: No such file or directory)
    - BASE: Android

workflows:
  deploy-ARM:
    envs:
      - BUILD_OPTS: "--disable-native-tests --build=arm-linux-gnueabi"
    after_run:
      - _deploy

  deploy-X86:
    envs:
      - BUILD_OPTS: "--disable-native-tests"
    after_run:
      - _deploy

  _deploy:
    steps:
      - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@8: {}
      - script@1.2:
        title: Checkout code
        inputs:
          - content: |-
              #!/bin/bash
              set -ex

              rm -rf tmp
              git clone --depth 10 https://github.com/openwall/john.git tmp
              cp -r tmp/. .
      - script@1.2:
        title: Building JtR
        inputs:
          - content: |-
              #!/bin/bash
              set -ex

              echo "----------------------------------------------------------------------"
              echo "Build options: $BUILD_OPTS"
              echo "----------------------------------------------------------------------"

              wget https://raw.githubusercontent.com/openwall/john-packages/release/tests/ci_controller.sh \
                -O .ci/ci_controller.sh
              chmod +x .ci/ci_controller.sh

              .ci/ci_controller.sh $TARGET_ARCH BUILD
              .ci/ci_controller.sh $TARGET_ARCH TEST

              mkdir -p "${BITRISE_DEPLOY_DIR}/${default_apk_name}/"
              mv README.md "${BITRISE_DEPLOY_DIR}/${default_apk_name}/"
              mv run "${BITRISE_DEPLOY_DIR}/${default_apk_name}/run"
              mv doc "${BITRISE_DEPLOY_DIR}/${default_apk_name}/doc"
      - deploy-to-bitrise-io:
        run_if: ".IsCI"
        inputs:
          - is_compress: "true"
          - deploy_path: "${BITRISE_DEPLOY_DIR}/${default_apk_name}"
meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: standard
